In [18]:
import pandas 
pandas.__version__

'1.1.0'

In [19]:
import numpy as np 
import pandas as pd 

In [20]:
## Pandas Series Object 
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [21]:
data.values 

array([0.25, 0.5 , 0.75, 1.  ])

In [22]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [23]:
data[1]
data[1:3]

0.5

1    0.50
2    0.75
dtype: float64

In [24]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], 
                index = ['a', 'b', 'c', 'd'])
data 

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [25]:
data['b']

0.5

In [26]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], 
                index=[2, 5, 3,7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [27]:
data[5]

0.5

In [28]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population 

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [29]:
population['California']

38332521

In [30]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [31]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [32]:
pd.Series(5, index=[100, 200, 300])


100    5
200    5
300    5
dtype: int64

In [33]:
pd.Series({2:'a', 1:'b', 3:'c'})


2    a
1    b
3    c
dtype: object

In [35]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

In [37]:
area_dict={'California': 423967, 
           'Texas': 695662,
           'New York': 141297,
           'Florida': 170312,
           'Illinois': 149995
          }

area = pd.Series(area_dict)
area 

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [40]:
states = pd.DataFrame({'population': population, 'area': area})
states 

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [41]:
states.index 

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [42]:
states.columns 

Index(['population', 'area'], dtype='object')

In [43]:
## DataFrame as specialized dictionary 
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [44]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [45]:
## From a list of dicts 
data = [{'a' : i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [46]:
pd.DataFrame([{'a': 1, 'b':2}, 
             {'b':3, 'c':4 }])


a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [47]:
## From a dictionary of Series objects 
pd.DataFrame({'population': population, 
             'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [48]:
## From a two-dimensional NumPy array 
pd.DataFrame(np.random.rand(3, 2), 
            columns=['foo', 'bar'], 
            index=['a', 'b', 'c'])


foo       bar
a  0.508254  0.722700
b  0.354096  0.022561
c  0.452653  0.377809

In [49]:
## From a NumPy structured array 
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A 

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [50]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [51]:
ind = pd.Index([2, 3, 5, 7, 11])
ind 

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [52]:
## Index as immutable array 
ind[1]

3

In [53]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [54]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [56]:
## index cannot be modified by normal means 
# ind[1]=0

In [60]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

## intersection 
indA & indB 
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

Int64Index([3, 5, 7], dtype='int64')

In [61]:
indA | indB ## union
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [64]:
indA ^ indB ## symmetric difference 
indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

Int64Index([1, 2, 9, 11], dtype='int64')

In [65]:
## Data Indexing and Selection 
## Series as dictionary 
import pandas as pd 
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data 

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [66]:
data['b']

0.5

In [67]:
'a' in data 

True

In [68]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [70]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [71]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [72]:
## Series as one-dimensional array 
## slicing by explicit index 
data['a': 'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [73]:
## Slicing by implicit integer index 
data[0:2]

a    0.25
b    0.50
dtype: float64

In [74]:
## Masking 
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [75]:
## Fancy indexing 
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

## Indexers: loc, iloc, and ix 


In [76]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data 

1    a
3    b
5    c
dtype: object

In [80]:
## Explicit index when indexing 
data[1]

'a'

In [81]:
data[1:3]

3    b
5    c
dtype: object

In [82]:
## 'loc' attribute indexing and slicing 
## explit index 
data.loc[1]

'a'

In [83]:
data.loc[1:3]

1    a
3    b
dtype: object

In [84]:
data

1    a
3    b
5    c
dtype: object

In [85]:
## 'iloc' attribute indexing and slicing 
data.iloc[1]
data.iloc[1:3]

'b'

3    b
5    c
dtype: object

In [88]:
## 'ix' hybrid of the two 
## explicit is better than implicit 
# data.ix[1]
# data.ix[1:3]

In [90]:
area = pd.Series({'California': 423967, 
                  'Texas': 695662,
                  'New York': 141297,
                  'Florida': 170312,
                  'Illinois': 149995})

pop = pd.Series({'California': 38332521,
                 'Texas': 26448193,
                 'New York': 19651127,
                 'Florida': 19552860,
                 'Illinois': 12882135})

data = pd.DataFrame({'area': area, 'pop': pop})
data 

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [91]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [92]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [94]:
## this method only work if the column name does not conflict with 
## DataFrame methods 
data.area is data['area']

True

In [95]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [96]:
## DataFrame as two-dimensional arary 
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [97]:
data.T 

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [98]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [99]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [100]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [101]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [105]:
# data.ix[:3, :'pop']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [110]:
data.loc[data.density > 100, ['pop', 'density']]

## and so on 
data.loc[(data.area < 300000) & (data.density < 12882135)]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [114]:
data.iloc[0, 2] = 90 
data
# data[0, 2] = 32
# data

area       pop     density  (0, 2)
California  423967  38332521   90.000000      32
Texas       695662  26448193   38.018740      32
New York    141297  19651127  139.076746      32
Florida     170312  19552860  114.806121      32
Illinois    149995  12882135   85.883763      32

### Additional indexing conventions 

In [115]:
data['Florida':'Illinois']

area       pop     density  (0, 2)
Florida   170312  19552860  114.806121      32
Illinois  149995  12882135   85.883763      32

In [116]:
data[1:3]

area       pop     density  (0, 2)
Texas     695662  26448193   38.018740      32
New York  141297  19651127  139.076746      32

In [117]:
## Direct masking are also row-wise  than column-wise 
data[data.density > 100]

area       pop     density  (0, 2)
New York  141297  19651127  139.076746      32
Florida   170312  19552860  114.806121      32

## Operating on Data in Pandas 


In [121]:
## Ufuncs: Index Preservation 
import pandas as pd 
import numpy as np 

rng = np.random.RandomState(42)
rng 
ser = pd.Series(rng.randint(0, 10, 4))
ser 

RandomState(MT19937) at 0x217A4ED0840

0    6
1    3
2    7
3    4
dtype: int32

In [122]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), 
                 columns=['A', 'B', 'C', 'D'])
df 

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [123]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [125]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [128]:
## UFuncs: Index Alignment 
## Index alignment in Series 

area = pd.Series({'Alaska': 1723337, 
                  'Texas': 695662,
                  'California': 423967}, name='area')

population = pd.Series({'California': 38332521,
                        'Texas': 26448193,
                        'New York': 19651127}, name='population')

area 
population 

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [129]:
population / area 

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [133]:
## Standard Python set arithmatic 
area.index | population.index 

area.index & population.index 

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

Index(['Texas', 'California'], dtype='object')

In [132]:
area.index  
population.index 

Index(['Alaska', 'Texas', 'California'], dtype='object')

Index(['California', 'Texas', 'New York'], dtype='object')

In [135]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 2, 5], index=[1, 2, 3])

A 
B 
A + B 

0    2
1    4
2    6
dtype: int64

1    1
2    2
3    5
dtype: int64

0    NaN
1    5.0
2    8.0
3    NaN
dtype: float64

In [136]:
## Fill some value instead of NaN values 
A.add(B, fill_value=0)

0    2.0
1    5.0
2    8.0
3    5.0
dtype: float64

In [137]:
## Index alignment in DataFrame 
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), 
                columns=list('AB'))
A 

A   B
0  1  11
1  5   1

In [138]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), 
                 columns=list('BAC')) 
B 

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [139]:
A + B 

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [143]:
fill = A.stack().mean()
fill 
A.add(B, fill_value=fill)

4.5

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

### Ufuncs: Operations Between DataFrame and Series 

In [144]:
A = rng.randint(10, size=(3, 4))
A 


array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [146]:
A[0]

array([3, 8, 2, 4])

In [145]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [147]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [149]:
df.subtract(df['R'], axis = 0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [152]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [153]:
df - halfrow 

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

## Handling Missing Data 

In [154]:
## None: Pythonic missing data 
import numpy as np 
import pandas as pd 

vals1 = np.array([1, None, 3, 4])
vals1 

array([1, None, 3, 4], dtype=object)

In [155]:
for dtype in ['object', 'int']: 
    print('dtype = ', dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype =  object
62.9 ms ± 264 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype =  int
2.74 ms ± 33.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [158]:
## will return the error 
# vals1.sum() 

In [159]:
## NaN: Missing numerrical data 
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [160]:
1 + np.nan 
0 * np.nan

nan

nan

In [161]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [162]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [164]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [165]:
x = pd.Series(range(2), dtype=int)
x 

0    0
1    1
dtype: int32

In [166]:
x[0] = None 
x 

0    NaN
1    1.0
dtype: float64

In [167]:
## Detecting null values 
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [168]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [169]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [171]:
## Dropping null values 
data 
data.dropna()

0        1
1      NaN
2    hello
3     None
dtype: object

0        1
2    hello
dtype: object

In [172]:
df = pd.DataFrame([[1, np.nan, 2], 
                  [2, 3, 5], 
                  [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [173]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [174]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [175]:
df[3] = np.nan 
df 

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [176]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [177]:
## Minimum number of non-null values to keep 
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [178]:
df 

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [179]:
## Filling null values
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [180]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [181]:
## forward-fill 
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [182]:
## backward-fill 
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [183]:
df 

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [190]:
df.fillna(method='ffill', axis=1)

## axis = 0 
df.fillna(method='ffill', axis=0)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  2.0  4.0  6 NaN

In [194]:
## backward fill along different axis 
df.fillna(method='bfill', axis=1)
df.fillna(method='bfill', axis=0)

0    1    2   3
0  1.0  2.0  2.0 NaN
1  2.0  3.0  5.0 NaN
2  4.0  4.0  6.0 NaN

0    1  2   3
0  1.0  3.0  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

0    1  2   3
0  1.0  3.0  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

## Hierarchical Indexing 

In [195]:
import pandas as pd 
import numpy as np

In [196]:
## the bad way 
index = [('California', 2000), 
         ('California', 2010),
         ('New York', 2000), 
         ('New York', 2010),
         ('Texas', 2000), 
         ('Texas', 2010)]


populations = [33871648, 
               37253956, 
               18976457, 
               19378102,
               20851820, 
               25145561]


pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [197]:
pop[('California', 2010):('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [198]:
## slicing is very difficult 
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [199]:
## The better way: Pandas MultiIndex 
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [200]:
pop = pop.reindex(index)
pop 

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [201]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [205]:
## convert it in to row and colun names 
pop_df = pop.unstack()
pop_df 

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [206]:
## convert into multiIndexing 
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [207]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [210]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18
f_u18.unstack()

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

### Methods of MultiIndex Creation 


In [212]:
df = pd.DataFrame(np.random.rand(4, 2), 
                  index=[['a', 'a', 'b', 'b'], 
                         [1, 2, 1, 2]], 
                  columns=['data1', 'data2'])
df 

data1     data2
a 1  0.308250  0.875984
  2  0.841520  0.834364
b 1  0.568208  0.430986
  2  0.493740  0.085623

In [213]:
data = {('California', 2000): 33871648, 
        ('California', 2010): 37253956, 
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}

pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [214]:
## Explicit MultiIndex constructors 
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], 
                          [1, 2, 1, 2]
                          ])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [215]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [219]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
              codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [221]:
## MultiIndex level names 
pop.index.names = ['state', 'year']
pop 

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [223]:
## MultiIndex for columns 
## heirarchical indices and columns 
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]], 
                                  names=['year', 'visit'])

columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], 
                                     ['HR', 'Temp']], 
                                    names=['subject', 'type'])

## Mock some data 
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10 
data += 37 

## Create the DataFrame 
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      34.0  37.1  33.0  36.5  38.0  35.9
     2      39.0  36.1  47.0  35.7  26.0  36.7
2014 1      28.0  38.5  35.0  36.5  54.0  36.5
     2      30.0  38.6  42.0  36.9  26.0  38.4

In [224]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      33.0  36.5
     2      47.0  35.7
2014 1      35.0  36.5
     2      42.0  36.9

In [225]:
## Indexing and Slicing a MultiIndex 
## Multiply indexed Series
pop 

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [226]:
pop['California', 2000]

33871648

In [227]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [228]:
pop.loc['California': 'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [229]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [230]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [231]:
## Selection based on fancy Indexing 
pop[['California', 'Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

#### Multiply Indexed DataFrames

In [232]:
health_data 

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      34.0  37.1  33.0  36.5  38.0  35.9
     2      39.0  36.1  47.0  35.7  26.0  36.7
2014 1      28.0  38.5  35.0  36.5  54.0  36.5
     2      30.0  38.6  42.0  36.9  26.0  38.4

In [233]:
health_data['Guido', 'HR']

year  visit
2013  1        33.0
      2        47.0
2014  1        35.0
      2        42.0
Name: (Guido, HR), dtype: float64

In [234]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      34.0  37.1
     2      39.0  36.1

In [235]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        34.0
      2        39.0
2014  1        28.0
      2        30.0
Name: (Bob, HR), dtype: float64

In [236]:
health_data.loc[(:, 1), (:, 'HR')]

SyntaxError: invalid syntax (<ipython-input-236-fb34fa30ac09>, line 1)

In [237]:
idx = pd.IndexSlice 
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      34.0  33.0  38.0
2014 1      28.0  35.0  54.0

### Rearranging Multi-Indices 


In [238]:
## Sorted and unsorted indices 
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.001495
      2      0.988218
c     1      0.575836
      2      0.436975
b     1      0.031222
      2      0.897808
dtype: float64

In [239]:
try: 
    data['a' : 'b']
except KeyError as e: 
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [240]:
data = data.sort_index()
data 

char  int
a     1      0.001495
      2      0.988218
b     1      0.031222
      2      0.897808
c     1      0.575836
      2      0.436975
dtype: float64

In [241]:
data['a':'b']

char  int
a     1      0.001495
      2      0.988218
b     1      0.031222
      2      0.897808
dtype: float64